from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

# 1. BASE MODELS (Shared properties)
class TaskBase(BaseModel):
    title: str = Field(..., example="Watch Kotlin Tutorial")
    description: Optional[str] = None
    is_complete: bool = False

class DayModuleBase(BaseModel):
    day_number: int = Field(..., example=1)
    topic: str = Field(..., example="Basics of Variables")
    is_locked: bool = True  # Default is locked!

class GoalBase(BaseModel):
    title: str = Field(..., example="Master Android Dev")
    category: str = Field(..., example="Career")

# 2. CREATE MODELS (What the User sends TO the API)
class TaskCreate(TaskBase):
    pass # No extra fields needed for creation

class GoalCreate(GoalBase):
    # When creating a goal, we might optionally send a list of days immediately
    pass

# 3. RESPONSE MODELS (What the API sends back to Android)
# This includes the database ID which is generated by the system
class TaskResponse(TaskBase):
    id: str # The unique ID from Neo4j

class DayResponse(DayModuleBase):
    id: str
    tasks: List[TaskResponse] = [] # Nested tasks for that day

class GoalResponse(GoalBase):
    id: str
    # We don't send ALL days at once to save data, 
    # but we could send the "current" day.